#' Constructor for \code{multiClassValidation} objects
#' 
#' \code{multiClassValidation} objects hold validation set predictions performed by different models.
#' 
#' \code{multiClassValidation} objects hold predictions performed by different models 
#' over the same validation set. A tag exist
#' to connect the predictions with the object that contains information about
#' the selected validation set. In addition the specific replicate index of the
#' validation set used is stored because several validation sets are contained in the
#' tagged object.
#' 
#' @param resample_indexes S3 object of class \code{datasetResample} with information
#'  about Class Labels and the data used using for training and predictions. Usually
#'  generated by the \code{generateTestIndexes} function.
#' @param prob List where each element contains a numeric vector with predictions performed 
#'  by a model on the same validation set. The numeric vector has the form 
#'  c(predictions_class1, predictions_class2, ..., predictions_classK) for 
#'  classification with K classes.
#' @param replicate_index Integer number that indicates which validation set was used.
#' 
#' @return S3 object of class \code{multiClassValidation}.
#' 
#' @family tgmMultiClass constructors
#' @seealso \code{\link{generateTestIndexes}}, 
multiClassValidation <- function(resample_indexes, prob, replicate_index){
  
  object <- list(class_labels = mcGet(resample_indexes, "class_labels"), 
                 prob = prob, 
                 datasetResample_tag = mcGet(resample_indexes, "tag"),
                 replicate_index = replicate_index)
  class(object) <- c("multiClassValidation")
  return(object)
  
}

#' Extract info from \code{multiClassValidation} objects
#' 
#' @export
mcGet.multiClassValidation <- function(x, attr, i = NULL){
  
  if (attr == "prob"){ # probability predictions
    
    if (is.null(i)){
      return(x[["prob"]])  
    } else {
      if (i >= 1 & i <= length(x[["prob"]])){
        result <- matrix(x[["prob"]][[i]], ncol = length(x[["class_labels"]]), byrow = FALSE)
        colnames(result) <- x[["class_labels"]]
        return(result)
      } else {
        stop("index i out of range.")
      }
    }
    
  } else if (attr == "number_models"){ # number of models that made predictions
    
    return(length(x[["prob"]]))
    
  } else if (attr == "class_labels"){ # class labels
    
    return(x[["class_labels"]])
    
  } else if (attr == "number_classes"){ # number of classes
    
    return(length(x[["class_labels"]]))
    
  } else if (attr == "tag"){ # resample indexes tag
    
    return(x[["datasetResample_tag"]])
    
  } else if (attr == "replicate_index"){ # Which validation set was used
    
    return(x[["replicate_index"]])
    
  } else {
    stop(attr, " not found.")
  }
  
}

