#' multi-class prediction probability with 'vgam'
#' 
#' \code{predict_r_vgam} apply \code{vgam} function to different training and test sets.
#' 
#' \code{predict_r_vgam} will then train with the training and validation
#' parts of the data using \code{vgam} and output the predicted probabilities
#' on the test sets.
#' 
#' @param resample_indexes An object that contains information about resampled 
#'  instances of \code{data}, usually generated by \code{\link{generateTestIndexes}}.
#' @param ... Arguments to be used in the \code{vgam} function.
#' 
#' @return It returns an S3 object of class c("multiClass_vgam", "multiClass").
#' This object contains the predicted probabilities for each test set. See 
#' the examples to get more info about how to extract the desired info from 
#' this object.     
#' 
#' @seealso \code{\link{generateTestIndexes}}
#' 
#' @examples
#' data(soccer_game)
#' indexes <- generateTestIndexes(dataset = soccer_game, 
#'                                target_names = c("home.win", "home.draw", "home.lose"), 
#'                                type = "3way", 
#'                                options = list(prop_v = 0.2, 
#'                                               prop_test = 0.2,
#'                                               number_replicates = 4))
#' pred_obj <- predict_r_vgam(resample_indexes = indexes,
#'                            formula = cbind(home.win, home.draw, home.lose) ~ 1 + fair.odd.home + fair.odd.draw + fair.odd.away, 
#'                            family = "multinomial")   
#' 
#' all_predictions <- mcGet(pred_obj, "prob")
#' second_replication_only <- mcGet(pred_obj, "prob", 2)
#' 
#' @export
predict_r_vgam <- function(resample_indexes, ...){
  
  installSuggestedPackage("VGAM")
  
  data <- mcGet(resample_indexes, "dataset")
  
  #training <- mcGet(resample_indexes, "training")
  #validation <- mcGet(resample_indexes, "validation")
  #test <- mcGet(resample_indexes, "test")
  tag <- mcGet(resample_indexes, "tag")
  
  number_replications <- mcGet(resample_indexes, "number_replicates")
  keep_probs <- list()
  
  for (i in 1:number_replications){

    training_data <- data[c(mcGet(resample_indexes, "training", i), mcGet(resample_indexes, "validation", i)), ]

    fit <- do.call(what = "vgam", args = list(data = training_data, ...))
    
    probs <- predict(fit, newdata = data[mcGet(resample_indexes, "test", i), ], type = "response")  
    keep_probs[[i]] <- c(probs)
    
  }
  
  class_labels <- colnames(probs)
  
  result <- multiClass(class_labels = class_labels, 
                       prob = keep_probs, 
                       datasetResample_tag = tag)
  
#   result <- list(class_labels = class_labels, 
#                  prob = keep_probs, 
#                  datasetResample_tag = tag)
  #class(result) <- c("multiClass_vgam", "multiClass")
  
  return(result)
  
}